version: '3.9'
services:
  db:
    image: mongo:4.2
    restart: always
    container_name: six-sities_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: test
    ports:
      - 27017:27017
    volumes:
      - six-sities_data:/data/db
volumes:
  six-sities_data:
